/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SerialMsg'
 * message type.
 */

public class SerialMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 5;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 137;

    /** Create a new SerialMsg of size 5. */
    public SerialMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SerialMsg of the given data_length. */
    public SerialMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg with the given data_length
     * and base offset.
     */
    public SerialMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg using the given byte array
     * as backing store.
     */
    public SerialMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SerialMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SerialMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg embedded in the given message
     * at the given base offset.
     */
    public SerialMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialMsg embedded in the given message
     * at the given base offset and length.
     */
    public SerialMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SerialMsg> \n";
      try {
        s += "  [alert_type=0x"+Long.toHexString(get_alert_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [x=0x"+Long.toHexString(get_x())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [y=0x"+Long.toHexString(get_y())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: alert_type
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'alert_type' is signed (false).
     */
    public static boolean isSigned_alert_type() {
        return false;
    }

    /**
     * Return whether the field 'alert_type' is an array (false).
     */
    public static boolean isArray_alert_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'alert_type'
     */
    public static int offset_alert_type() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'alert_type'
     */
    public static int offsetBits_alert_type() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'alert_type'
     */
    public short get_alert_type() {
        return (short)getUIntBEElement(offsetBits_alert_type(), 8);
    }

    /**
     * Set the value of the field 'alert_type'
     */
    public void set_alert_type(short value) {
        setUIntBEElement(offsetBits_alert_type(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'alert_type'
     */
    public static int size_alert_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'alert_type'
     */
    public static int sizeBits_alert_type() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: x
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'x' is signed (false).
     */
    public static boolean isSigned_x() {
        return false;
    }

    /**
     * Return whether the field 'x' is an array (false).
     */
    public static boolean isArray_x() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'x'
     */
    public static int offset_x() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'x'
     */
    public static int offsetBits_x() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'x'
     */
    public int get_x() {
        return (int)getUIntBEElement(offsetBits_x(), 16);
    }

    /**
     * Set the value of the field 'x'
     */
    public void set_x(int value) {
        setUIntBEElement(offsetBits_x(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'x'
     */
    public static int size_x() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'x'
     */
    public static int sizeBits_x() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: y
    //   Field type: int, unsigned
    //   Offset (bits): 24
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'y' is signed (false).
     */
    public static boolean isSigned_y() {
        return false;
    }

    /**
     * Return whether the field 'y' is an array (false).
     */
    public static boolean isArray_y() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'y'
     */
    public static int offset_y() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'y'
     */
    public static int offsetBits_y() {
        return 24;
    }

    /**
     * Return the value (as a int) of the field 'y'
     */
    public int get_y() {
        return (int)getUIntBEElement(offsetBits_y(), 16);
    }

    /**
     * Set the value of the field 'y'
     */
    public void set_y(int value) {
        setUIntBEElement(offsetBits_y(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'y'
     */
    public static int size_y() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'y'
     */
    public static int sizeBits_y() {
        return 16;
    }

}
